valid:
  email:
    max_length: 255
  name:
    max_length: 100
  password:
    min_length: 6
  category:
    name:
      max_length: 100
remember: "1"
limit_page:
  users: 10
  news: 3
  top_rates: 4
  top_views: 8
  booking: 10
format_time: "%-d/%-m/%y: %H:%M"
locale_en: "en"
size_img:
  tour: "400x400"
  home: "262x200"
